replicas: 2

args:
  - --kubelet-insecure-tls
  - --kubelet-preferred-address-types=InternalIP,InternalDNS,hostname,ExternalIP

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi

nodeSelector:
  kubernetes.io/os: linux

tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"