defaultRules:
  create: true

grafana:
  enabled: true
  persistence:
    enabled: true
    type: pvc
    storageClassName: gp3
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  ingress:
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /api/health
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    enabled: true
    ingressClassName: alb
    paths:
    - /

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheus:
  prometheusSpec:
    retention: 10d
    retentionSize: 50GB
    scrapeInterval: 15s
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
    additionalScrapeConfigs:
      - job_name: "node-to-node-latency"
        metrics_path: /probe
        params:
          module: [icmp]
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter.monitoring.svc.cluster.local:9115

alertmanager:
  enabled: true
  persistence:
    enabled: true
    storageClassName: gp3
    accessModes:
      - ReadWriteOnce
    size: 2Gi