replicaCount: 1

image:
  repository: node
  pullPolicy: IfNotPresent
  tag: "20-alpine"

nameOverride: "node-ws"
fullnameOverride: ""

service:
  port: 3000

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200"

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: false
  storageClass: gp3
  size: 5Gi
  accessMode: ReadWriteOnce
  mountPath: /data

otel:
  # Tells the OTel Operator to inject the Node.js SDK into this pod at startup
  inject: true
  serviceName: node-ws
  collectorEndpoint: "http://opentelemetry-collector.monitoring:4318"
